# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-18 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseProspectiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('objetivo', models.TextField()),
            ],
            options={
                'verbose_name': 'Fase Prospectiva',
                'verbose_name_plural': 'Fases Prospectivas',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('caracter', models.CharField(choices=[('Neutro', 'Neutro'), ('Moderado', 'Moderado'), ('Urgente', 'Urgente')], default='Neutro', max_length=20, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('enviadoMultiple', models.BooleanField(default=False)),
                ('hijoMultiple', models.BooleanField(default=False)),
                ('idEstudio', models.PositiveIntegerField(null=True)),
                ('tipoEstudio', models.CharField(max_length=50, null=True)),
                ('idDestinatarios', models.ManyToManyField(related_name='mensaje_dest', to=settings.AUTH_USER_MODEL, verbose_name='idDestinatarios')),
                ('idEmisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes del proyecto',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('objetivo', models.TextField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
                ('idAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_administrador', to=settings.AUTH_USER_MODEL, verbose_name='administrador')),
                ('idCoordinadores', models.ManyToManyField(related_name='proyecto_coordinadores_set', to=settings.AUTH_USER_MODEL, verbose_name='coordinadores')),
                ('idExpertos', models.ManyToManyField(blank=True, related_name='proyecto_expertos_set', to=settings.AUTH_USER_MODEL, verbose_name='expertos')),
            ],
            options={
                'verbose_name': 'Proyecto prospectivo',
                'verbose_name_plural': 'Proyectos prospectivos',
            },
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Cuantitativa', 'Cuantitativa'), ('Cualitativa', 'Cualitativa'), ('Semi-cuantitativa', 'Semi-cuantitativa')], max_length=20, null=True)),
                ('objetivo', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Tecnica Prospectiva',
                'verbose_name_plural': 'Tecnicas Prospectivas',
            },
        ),
        migrations.AddField(
            model_name='mensaje',
            name='idProyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together=set([('nombre', 'idAdministrador')]),
        ),
    ]
