# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='tipoEstudio',
            field=models.IntegerField(null=True),
        ),
    ]
