# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20200109_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnica',
            name='codigo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
