# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_tecnica_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnica',
            name='codigo',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
