# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20200121_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha',
            new_name='fechaHora',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='enviadoMultiple',
            new_name='multiples',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='caracter',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipoEstudio',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
