# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20200122_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='enviadoMultiples',
            field=models.BooleanField(default=False),
        ),
    ]
