# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-24 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_mensaje_enviadomultiples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='idEstudio',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipoEstudio',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
