# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-25 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_mensaje_usuarioemisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='usuarioEmisor',
        ),
    ]
