# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_remove_mensaje_usuarioemisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='tituloEstudio',
            field=models.TextField(default='Sin estudio'),
        ),
    ]
