# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoeficienteAlfa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('num_expertos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Coeficiente Alfa de Cronbach',
                'verbose_name_plural': 'Coeficiente Alfa de Cronbach',
            },
        ),
        migrations.CreateModel(
            name='EstudioEntrevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('entrevistador', models.CharField(blank=True, max_length=50, null=True)),
                ('entrevistado', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('idProyecto', models.PositiveIntegerField(default=1)),
                ('idAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ent_administrador', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('idCoordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ent_coordinador', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador')),
                ('idExpertos', models.ManyToManyField(related_name='ent_expertos_set', to=settings.AUTH_USER_MODEL, verbose_name='Expertos')),
            ],
            options={
                'verbose_name': 'Estudio entrevista',
                'verbose_name_plural': 'Estudios entrevista',
            },
        ),
        migrations.CreateModel(
            name='Juicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('idExperto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Juicio de expertos',
                'verbose_name_plural': 'Juicios de los expertos',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('texto_respuesta', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('idEstudio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entrevista.EstudioEntrevista')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='RondaJuicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ronda', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('numero_preguntas', models.IntegerField(default=1)),
                ('idEstudio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entrevista.EstudioEntrevista')),
            ],
            options={
                'verbose_name': 'Ronda de juicio',
                'verbose_name_plural': 'Rondas de juicio',
            },
        ),
        migrations.CreateModel(
            name='ValorEscalaLikert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('valor', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('idEstudio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entrevista.EstudioEntrevista')),
            ],
            options={
                'verbose_name': 'Escala de Likert',
                'verbose_name_plural': 'Escala de Likert',
            },
        ),
        migrations.AddField(
            model_name='juicio',
            name='idRonda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entrevista.RondaJuicio'),
        ),
        migrations.AddField(
            model_name='juicio',
            name='idValorEscala',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entrevista.ValorEscalaLikert'),
        ),
        migrations.AddField(
            model_name='coeficientealfa',
            name='idRonda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entrevista.RondaJuicio'),
        ),
        migrations.AlterUniqueTogether(
            name='valorescalalikert',
            unique_together=set([('nombre', 'valor', 'idEstudio'), ('valor', 'idEstudio'), ('nombre', 'idEstudio')]),
        ),
        migrations.AlterUniqueTogether(
            name='rondajuicio',
            unique_together=set([('numero_ronda', 'idEstudio')]),
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together=set([('texto_pregunta', 'idEstudio')]),
        ),
        migrations.AlterUniqueTogether(
            name='juicio',
            unique_together=set([('texto_pregunta', 'idExperto', 'idRonda')]),
        ),
    ]
