# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorescalalikert',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
