# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0002_valorescalalikert_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valorescalalikert',
            unique_together=set([('valor', 'estado', 'idEstudio'), ('nombre', 'valor', 'estado', 'idEstudio')]),
        ),
    ]
