# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0003_auto_20180915_2011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valorescalalikert',
            unique_together=set([('valor', 'estado', 'idEstudio'), ('nombre', 'estado', 'idEstudio'), ('nombre', 'valor', 'estado', 'idEstudio')]),
        ),
    ]
