# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0004_auto_20180919_0917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valorescalalikert',
            unique_together=set([('nombre', 'valor', 'estado', 'idEstudio')]),
        ),
    ]
