# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0005_auto_20180919_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudioentrevista',
            name='slug',
            field=models.SlugField(default='slug prueb', max_length=100),
            preserve_default=False,
        ),
    ]
