# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0006_estudioentrevista_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudioentrevista',
            name='slug',
        ),
    ]
