# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('entrevista', '0007_remove_estudioentrevista_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudioentrevista',
            name='tipoTecnica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Tecnica'),
        ),
        migrations.AlterField(
            model_name='estudioentrevista',
            name='idProyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
        migrations.AlterField(
            model_name='estudioentrevista',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='estudioentrevista',
            unique_together=set([('titulo', 'tipoTecnica', 'idProyecto')]),
        ),
    ]
