# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-05 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0008_auto_20191218_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudioentrevista',
            name='fecha_final',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
