# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0009_auto_20200105_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
