# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-07 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0010_pregunta_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valorescalalikert',
            unique_together=set([('nombre', 'estado', 'idEstudio'), ('nombre', 'valor', 'estado', 'idEstudio')]),
        ),
    ]
