# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0014_estudioentrevista_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudioentrevista',
            name='codigo',
        ),
    ]
