# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-08 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioValoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevaValoracion', models.TextField(verbose_name=(('V', 'Actitud muy favorable'), ('v', 'Actitud favorable'), ('A', 'Actitud neutra'), ('r', 'Actitud desfavorable'), ('R', 'Actitud muy desfavorable'), ('B', 'Se quiere participar sin opinar'), ('N', 'No se quiere participar')))),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('fechaHora', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cambio Valoracion Idea',
                'verbose_name_plural': 'Cambios Valoraciones Ideas',
            },
        ),
        migrations.CreateModel(
            name='EstudioAbaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tematica', models.TextField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
                ('idAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abaco_administrador', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('idCoordinadores', models.ManyToManyField(related_name='abaco_coordinadores_set', to=settings.AUTH_USER_MODEL, verbose_name='Coordinadores')),
                ('idExpertos', models.ManyToManyField(related_name='abaco_expertos_set', to=settings.AUTH_USER_MODEL, verbose_name='Expertos')),
                ('idProyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
                ('tipoTecnica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Tecnica')),
            ],
            options={
                'verbose_name': 'Estudio Abaco de Regnier',
                'verbose_name_plural': 'Estudios Abaco de Regnier',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('idEstudio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abaco.EstudioAbaco')),
                ('idProponente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
            },
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('idEstudio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abaco.EstudioAbaco')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
            },
        ),
        migrations.CreateModel(
            name='ValoracionIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.TextField(verbose_name=(('V', 'Actitud muy favorable'), ('v', 'Actitud favorable'), ('A', 'Actitud neutra'), ('r', 'Actitud desfavorable'), ('R', 'Actitud muy desfavorable'), ('B', 'Se quiere participar sin opinar'), ('N', 'No se quiere participar')))),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('idExperto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idIdea', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abaco.Idea')),
            ],
            options={
                'verbose_name': 'Valoracion Idea',
                'verbose_name_plural': 'Valoraciones Ideas',
            },
        ),
        migrations.AddField(
            model_name='cambiovaloracion',
            name='idValoracion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abaco.ValoracionIdea'),
        ),
        migrations.AlterUniqueTogether(
            name='valoracionidea',
            unique_together=set([('idIdea', 'idExperto')]),
        ),
        migrations.AlterUniqueTogether(
            name='regla',
            unique_together=set([('titulo', 'idEstudio')]),
        ),
        migrations.AlterUniqueTogether(
            name='idea',
            unique_together=set([('titulo', 'idEstudio')]),
        ),
        migrations.AlterUniqueTogether(
            name='estudioabaco',
            unique_together=set([('titulo', 'tipoTecnica', 'idProyecto')]),
        ),
    ]
