# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0003_auto_20200108_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudioabaco',
            name='codigo',
            field=models.IntegerField(default=3),
        ),
    ]
