# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0004_estudioabaco_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regla',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
