# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0006_auto_20200110_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudioabaco',
            name='estadoValoraciones',
            field=models.BooleanField(default=False),
        ),
    ]
