# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0007_estudioabaco_estadovaloraciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regla',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
