# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-11 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0008_auto_20200110_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambiovaloracion',
            name='idValoracion',
        ),
        migrations.AddField(
            model_name='valoracionidea',
            name='fechaHora',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CambioValoracion',
        ),
    ]
