# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-11 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0009_auto_20200110_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionidea',
            name='cambio',
            field=models.BooleanField(default=False),
        ),
    ]
