# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-11 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0010_valoracionidea_cambio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoracionidea',
            old_name='cambio',
            new_name='estado',
        ),
    ]
