# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-11 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0011_auto_20200111_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoracionidea',
            options={'verbose_name': 'Valoracion Idea', 'verbose_name_plural': 'Valoraciones Ideas registradas'},
        ),
    ]
