# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0012_auto_20200111_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionidea',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
