# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0013_auto_20200111_1136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valoracionidea',
            unique_together=set([]),
        ),
    ]
