# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0014_auto_20200111_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionidea',
            name='fechaHora',
            field=models.DateTimeField(),
        ),
    ]
