# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0015_auto_20200111_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionidea',
            name='fechaHora',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 2, 9, 55, 90710, tzinfo=utc)),
        ),
    ]
