# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0016_auto_20200111_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionidea',
            name='fechaHora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
