# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0017_auto_20200111_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Escala Cromática',
                'verbose_name_plural': 'Escalas Cromáticas',
            },
        ),
        migrations.CreateModel(
            name='OpcionEscala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('abreviacion', models.CharField(max_length=1)),
                ('descripcion', models.TextField()),
                ('idEscala', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abaco.Escala')),
            ],
            options={
                'verbose_name': 'Opción Escala Cromática',
                'verbose_name_plural': 'Oopciones Escalas Cromáticas',
            },
        ),
        migrations.AlterField(
            model_name='valoracionidea',
            name='justificacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='valoracionidea',
            name='valoracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abaco.OpcionEscala'),
        ),
        migrations.AddField(
            model_name='estudioabaco',
            name='idEscala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abaco.Escala'),
        ),
        migrations.AlterUniqueTogether(
            name='opcionescala',
            unique_together=set([('nombre', 'abreviacion', 'idEscala')]),
        ),
    ]
