# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0019_auto_20200112_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionescala',
            name='codigoColor',
            field=models.TextField(null=True),
        ),
    ]
