# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-13 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0021_auto_20200112_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionidea',
            name='justificacion',
            field=models.TextField(default='B'),
        ),
        migrations.AlterField(
            model_name='valoracionidea',
            name='valoracion',
            field=models.TextField(),
        ),
    ]
