# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0023_auto_20200113_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudioabaco',
            name='codigo',
        ),
    ]
