# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0024_remove_estudioabaco_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.IntegerField()),
                ('tipo', models.TextField(choices=[('0', 'Registro de ideas'), ('1', 'Depuración de ideas'), ('2', 'Valoración de ideas')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sesion de ábaco de Regnier',
                'verbose_name_plural': 'Sesiones de ábaco de Regnier',
            },
        ),
        migrations.RemoveField(
            model_name='estudioabaco',
            name='estadoValoraciones',
        ),
        migrations.AddField(
            model_name='sesion',
            name='idEstudio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abaco.EstudioAbaco'),
        ),
        migrations.AlterUniqueTogether(
            name='sesion',
            unique_together=set([('numero_sesion', 'idEstudio')]),
        ),
    ]
