# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-27 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0025_auto_20200127_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionescala',
            options={'verbose_name': 'Opción Escala Cromática', 'verbose_name_plural': 'Opciones Escalas Cromáticas'},
        ),
        migrations.AlterField(
            model_name='sesion',
            name='tipo',
            field=models.IntegerField(choices=[('0', 'Registro de ideas'), ('1', 'Depuración de ideas'), ('2', 'Valoración de ideas')]),
        ),
    ]
