# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-04 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaco', '0026_auto_20200127_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Registro o edición de ideas'), (1, 'Selección de ideas'), (2, 'Valoración de ideas')]),
        ),
    ]
