# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('coordinadores', models.ManyToManyField(related_name='cuestionario_cordinadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
            },
        ),
        migrations.CreateModel(
            name='Delphi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objetivos', models.TextField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField()),
                ('estado', models.BooleanField()),
                ('slug', models.SlugField(unique=True)),
                ('coordinadores', models.ManyToManyField(related_name='Delphi_coordinadores', to=settings.AUTH_USER_MODEL)),
                ('expertos', models.ManyToManyField(related_name='Delphi_expertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delphi',
                'verbose_name_plural': 'Delphi',
            },
        ),
        migrations.CreateModel(
            name='RondasDelphi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('abierto', models.BooleanField(default=True, help_text='Dice si se pueden votar o no las preguntas.')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('coordinadores', models.ManyToManyField(related_name='ronda_cordinadores', to=settings.AUTH_USER_MODEL)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delphi.Cuestionario', verbose_name='Cuestionario')),
                ('delphi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ronda_delphi', to='delphi.Delphi')),
                ('expertos', models.ManyToManyField(related_name='ronda_expertos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='delphi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuestionario_delphi', to='delphi.Delphi'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='expertos',
            field=models.ManyToManyField(related_name='cuestionario_expertos', to=settings.AUTH_USER_MODEL),
        ),
    ]
