# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-28 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0010_mensaje_tituloestudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortNameA', models.CharField(default='', max_length=10, verbose_name='Nombre Corto Acción')),
                ('longNameA', models.CharField(default='', max_length=50, verbose_name='Nombre Largo Acción')),
                ('descriptionA', models.TextField(default='', max_length=100, verbose_name='Descripción Acción')),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortNameC', models.CharField(default='', max_length=10, verbose_name='Nombre Corto Critetio')),
                ('longNameC', models.CharField(default='', max_length=50, verbose_name='Nombre Largo Criterio')),
                ('pesoC', models.IntegerField(default=0, verbose_name='Peso Criterio')),
                ('descriptionC', models.TextField(default='', max_length=100, verbose_name='Descripción Criterio')),
            ],
            options={
                'verbose_name': 'Criterio',
                'verbose_name_plural': 'Criterios',
            },
        ),
        migrations.CreateModel(
            name='EstudioMultipol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=25, verbose_name='Título')),
                ('descripcion', models.TextField(default='', max_length=200, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
                ('idAdministrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Administrador', to=settings.AUTH_USER_MODEL)),
                ('idCoordinador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coordinadores', to=settings.AUTH_USER_MODEL)),
                ('idExpertos', models.ManyToManyField(related_name='Expertos', to=settings.AUTH_USER_MODEL)),
                ('idProyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
                ('tipoTecnica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Tecnica')),
            ],
            options={
                'verbose_name': 'Estudio Multipol',
                'verbose_name_plural': 'Estudios Multipol',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracionCA', models.PositiveIntegerField(default=0, verbose_name='Valoración')),
                ('opinion', models.CharField(default='', max_length=200, verbose_name='Opinión')),
                ('accion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipol.Accion')),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipol.Criterio')),
                ('estudio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipol.EstudioMultipol')),
            ],
            options={
                'verbose_name': 'Evaluación Criterio/Acción',
                'verbose_name_plural': 'Evaluaciones Criterio/Acción',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracionCP', models.PositiveIntegerField(default=0, verbose_name='Valoración')),
                ('opinion', models.CharField(default='', max_length=200, null=True, verbose_name='Opinión')),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipol.Criterio')),
                ('estudio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipol.EstudioMultipol')),
            ],
            options={
                'verbose_name': 'Evaluación Criterio/Política',
            },
        ),
        migrations.CreateModel(
            name='InformeFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('informe', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('idEstudio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='multipol.EstudioMultipol')),
            ],
            options={
                'verbose_name': 'Informe final',
                'verbose_name_plural': 'Informes finales',
            },
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortNameP', models.CharField(default='', max_length=10, verbose_name='Nombre Corto Política')),
                ('longNameP', models.CharField(default='', max_length=50, verbose_name='Nombre Largo Política')),
                ('pesoP', models.IntegerField(default=0, verbose_name='Peso Política')),
                ('descriptionP', models.TextField(default='', max_length=100, verbose_name='Descripción Política')),
                ('estudio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipol.EstudioMultipol')),
            ],
            options={
                'verbose_name': 'Política',
                'verbose_name_plural': 'Políticas',
            },
        ),
        migrations.AddField(
            model_name='evaluacioncp',
            name='politica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipol.Politica'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='estudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipol.EstudioMultipol'),
        ),
        migrations.AddField(
            model_name='accion',
            name='estudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipol.EstudioMultipol'),
        ),
    ]
