# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-13 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_mensaje_tituloestudio'),
        ('multipol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiomultipol',
            name='dias_finalizacion_informe',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='estudiomultipol',
            unique_together=set([('titulo', 'tipoTecnica', 'idProyecto')]),
        ),
    ]
