# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipol', '0002_auto_20210513_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionca',
            name='opinion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Opinión'),
        ),
        migrations.AlterField(
            model_name='evaluacionca',
            name='valoracionCA',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Valoración'),
        ),
    ]
