# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mactor', '0002_auto_20180619_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiomactor',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
