# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mactor', '0004_auto_20180811_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nombreLargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='nombreLargo',
            field=models.CharField(max_length=100),
        ),
    ]
