# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mactor', '0005_auto_20180812_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiomactor',
            name='diasFinalizacionInforme',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
