# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mactor', '0007_auto_20180907_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relacionmid',
            options={'verbose_name': 'Relacion de Influencia Directa', 'verbose_name_plural': 'Relaciones de Influencia Directa'},
        ),
    ]
