# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-18 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('mactor', '0008_auto_20180911_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relacionmid',
            options={'verbose_name': 'Relacion de Influencia', 'verbose_name_plural': 'Relaciones de influencia'},
        ),
        migrations.AddField(
            model_name='estudiomactor',
            name='tipoTecnica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Tecnica'),
        ),
        migrations.AlterField(
            model_name='estudiomactor',
            name='idProyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
        migrations.AlterField(
            model_name='estudiomactor',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='relacionmao',
            name='justificacion',
            field=models.TextField(default='Justificación de la relación entre el actor y el objetivo'),
        ),
        migrations.AlterField(
            model_name='relacionmid',
            name='justificacion',
            field=models.TextField(default='Justificación de la relación entre los actores'),
        ),
        migrations.AlterUniqueTogether(
            name='estudiomactor',
            unique_together=set([('titulo', 'tipoTecnica', 'idProyecto')]),
        ),
    ]
