# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mactor', '0009_auto_20191218_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiomactor',
            name='codigo',
            field=models.IntegerField(default=1),
        ),
    ]
