# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mactor', '0010_estudiomactor_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiomactor',
            name='codigo',
        ),
    ]
