# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-04 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0010_mensaje_tituloestudio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioLluviaDeIdeas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tematica', models.TextField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
                ('idAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lluvia_administrador', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('idCoordinador', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lluvia_coordinador', to=settings.AUTH_USER_MODEL, verbose_name='coordinador')),
                ('idExpertos', models.ManyToManyField(related_name='lluvia_participantes_set', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
                ('idProyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
                ('tipoTecnica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Tecnica')),
            ],
            options={
                'verbose_name': 'Estudio Lluvia de Ideas',
                'verbose_name_plural': 'Estudios Lluvia de ideas',
            },
        ),
        migrations.CreateModel(
            name='EtapaPlanAccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Etapa del plan de acción',
                'verbose_name_plural': 'Etapas del plan de acción',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now=True)),
                ('estado', models.BooleanField(default=False)),
                ('idCreador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creador_idea_set', to=settings.AUTH_USER_MODEL)),
                ('idEstudio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='brainstorming.EstudioLluviaDeIdeas')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
            },
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('idEstudio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='brainstorming.EstudioLluviaDeIdeas')),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('permitir_ideas', models.BooleanField(default=False, help_text='Indica si se puede llevar a cabo la creación de ideas, si esta desactivado se puede votar por las ideas ya creadas.')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True, help_text='Indica si se pueden votar o no las ideas.')),
                ('idEstudio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='brainstorming.EstudioLluviaDeIdeas')),
            ],
            options={
                'verbose_name': 'Sesion de lluvia de ideas',
                'verbose_name_plural': 'Sesiones de lluvia de ideas',
            },
        ),
        migrations.CreateModel(
            name='ValoracionIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.BooleanField(default=False)),
                ('justificacion', models.TextField()),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('idIdea', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='brainstorming.Idea')),
                ('idParticipante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoracion_participante_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoracion Idea',
                'verbose_name_plural': 'Valoraciones Ideas registradas',
            },
        ),
        migrations.AddField(
            model_name='etapaplanaccion',
            name='idIdea',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='brainstorming.Idea'),
        ),
        migrations.AlterUniqueTogether(
            name='sesion',
            unique_together=set([('numero_sesion', 'idEstudio')]),
        ),
        migrations.AlterUniqueTogether(
            name='regla',
            unique_together=set([('titulo', 'idEstudio')]),
        ),
        migrations.AlterUniqueTogether(
            name='idea',
            unique_together=set([('titulo', 'idEstudio')]),
        ),
        migrations.AlterUniqueTogether(
            name='etapaplanaccion',
            unique_together=set([('numero', 'titulo', 'idIdea')]),
        ),
        migrations.AlterUniqueTogether(
            name='estudiolluviadeideas',
            unique_together=set([('titulo', 'tipoTecnica', 'idProyecto')]),
        ),
    ]
