# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-23 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Nombre Corto Acción')),
                ('long_name', models.CharField(max_length=50, verbose_name='Nombre Largo Acción')),
                ('description', models.TextField(max_length=100, verbose_name='Descripción Acción')),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Nombre Corto Critetio')),
                ('long_name', models.CharField(max_length=50, verbose_name='Nombre Largo Criterio')),
                ('peso', models.IntegerField(default=1, verbose_name='Peso Criterio')),
                ('description', models.TextField(max_length=100, verbose_name='Descripción Criterio')),
            ],
            options={
                'verbose_name': 'Criterio',
                'verbose_name_plural': 'Criterios',
            },
        ),
        migrations.CreateModel(
            name='EstudioMultipol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25, verbose_name='Título')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
                ('dias_finalizacion_informe', models.PositiveIntegerField(default=5)),
                ('idAdministrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrador_estudio_multipol', to=settings.AUTH_USER_MODEL)),
                ('idCoordinador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_estudio_multipol', to=settings.AUTH_USER_MODEL)),
                ('idExpertos', models.ManyToManyField(related_name='expertos_estudio_multipol', to=settings.AUTH_USER_MODEL)),
                ('idProyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_estudio_multipol', to='proyecto.Proyecto')),
                ('tipoTecnica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnica_estudio_multipol', to='proyecto.Tecnica')),
            ],
            options={
                'verbose_name': 'Multipol',
                'verbose_name_plural': 'Multipols',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCriterioAccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Valoración')),
                ('opinion', models.CharField(blank=True, max_length=200, verbose_name='Opinión')),
                ('accion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipolv1.Accion')),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipolv1.Criterio')),
                ('estudio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipolv1.EstudioMultipol')),
                ('experto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación Criterio Acción',
                'verbose_name_plural': 'Evaluaciones Criterio Acción',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCriterioPolitica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField(default=0, verbose_name='Valoración')),
                ('opinion', models.CharField(max_length=200, verbose_name='evaluaciones')),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipolv1.Criterio')),
                ('estudio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipolv1.EstudioMultipol')),
                ('experto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación Criterio/Política',
            },
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Nombre Corto Política')),
                ('long_name', models.CharField(max_length=50, verbose_name='Nombre Largo Política')),
                ('peso', models.IntegerField(default=1, verbose_name='Peso Política')),
                ('description', models.TextField(max_length=100, verbose_name='Descripción Política')),
                ('estudio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politicas', to='multipolv1.EstudioMultipol')),
            ],
            options={
                'verbose_name': 'Política',
                'verbose_name_plural': 'Políticas',
            },
        ),
        migrations.AddField(
            model_name='evaluacioncriteriopolitica',
            name='politica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multipolv1.Politica'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='estudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='multipolv1.EstudioMultipol'),
        ),
        migrations.AddField(
            model_name='accion',
            name='estudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accions', to='multipolv1.EstudioMultipol'),
        ),
        migrations.AlterUniqueTogether(
            name='estudiomultipol',
            unique_together=set([('titulo', 'tipoTecnica', 'idProyecto')]),
        ),
    ]
